SELECT PAR.CODPARC AS "Parceiro ID",
       PAR.RAZAOSOCIAL AS "Parceiro",
       CID.CODCID AS "Cidade ID",
       CID.NOMECID AS "Cidade",
       UF.UF AS "Estado ID",
       UF.DESCRICAO AS "Estado",
       TPP.CODTIPPARC AS "Perfil ID",
       TPP.DESCRTIPPARC AS "Perfil"
FROM TGFPAR PAR
LEFT JOIN TSICID CID ON CID.CODCID = PAR.CODCID
LEFT JOIN TSIUFS UF ON UF.CODUF = CID.UF
LEFT JOIN TGFTPP TPP ON PAR.CODTIPPARC = TPP.CODTIPPARC
