SELECT TO_CHAR(CASE WHEN TGFTOP.GOLSINAL = -1
       AND TGFTOP.GOLDEV = -1 THEN TGFCAB.DTNEG ELSE TGFCAB.DTNEG END , 'DD/MM/YYYY') AS "Dia",
       TGFCAB.NUNOTA AS "Nunota ID",
       TGFCAB.NUNOTA AS "Nunota",
       EMP.CODEMP AS "Empresa ID",
       EMPE.RAZAOSOCIAL AS "Empresa",
       TGFCAB.CODPARC AS "Parceiro ID",
       ITE.CODPROD AS "Produto ID",
       TGFCAB.CODVEND AS "Vendedor ID",
       TGFCAB.CODNAT AS "Natureza ID",
       TGFCAB.CODCENCUS AS "Centro de Resultado ID",
       TGFCAB.CODTIPOPER AS "Tipo de Operação ID",
             ((ITE.VLRTOT - ITE.VLRDESC - NVL(ITE.VLRREPRED,0) + ITE.VLRSUBST + ITE.VLRIPI) * VCA.INDITENS) * CASE WHEN TGFTOP.BONIFICACAO = 'S' THEN 0 ELSE 1 END * TGFTOP.GOLDEV AS "Vendas",
              NVL((
                  (SELECT MAX(CUS.ENTRADASEMICMS)
                   FROM TGFCUS CUS
                   WHERE CUS.CODPROD = ITE.CODPROD
                     AND ITE.CODEMP = CUS.CODEMP
                     AND CUS.DTATUAL =
                       (SELECT MAX (CN.DTATUAL)
                        FROM TGFCUS CN
                        WHERE CN.CODPROD = CUS.CODPROD
                          AND CN.DTATUAL <= TGFCAB.DTNEG
                          AND CN.CODLOCAl = CUS.CODLOCAL
                          AND CN.CODEMP = CUS.CODEMP))), (ITE.VLRTOT - ITE.VLRDESC + ITE.VLRSUBST + ITE.VLRIPI) * VCA.INDITENS / (CASE WHEN ITE.QTDNEG=0 THEN 1 ELSE ITE.QTDNEG END)) * ITE.QTDNEG * TGFTOP.GOLDEV AS "CMV",
      
       ((((ITE.VLRTOT - ITE.VLRDESC - NVL(ITE.VLRREPRED,0) + ITE.VLRSUBST + ITE.VLRIPI) * VCA.INDITENS) * CASE WHEN TGFTOP.BONIFICACAO = 'S' THEN 0 ELSE 1 END) - ((((((ITE.VLRTOT - ITE.VLRDESC - NVL(ITE.VLRREPRED,0)) * VCA.INDITENS * ((CASE WHEN CGM.TEMPERCPARTSIMP = 'S' THEN (CASE WHEN TGFTOP.TEMPIS = 'S' THEN NVL(CGM.PERCPIS,0) ELSE 0 END) ELSE (CASE WHEN NVL(CGM.PERCPIS, 0) = 0 THEN 0 WHEN TGFTOP.TEMPIS = 'S'
AND NOT EXISTS
  (SELECT(1)
   FROM TGFDIN DIN
   WHERE DIN.CODIMP = 6
     AND DIN.NUNOTA = ITE.NUNOTA
     AND DIN.SEQUENCIA = ITE.SEQUENCIA) THEN NVL(CGM.PERCPIS, 0) ELSE 0 END) END) + (CASE WHEN CGM.TEMPERCPARTSIMP = 'S' THEN (CASE WHEN TGFTOP.TEMCSL = 'S' THEN NVL(CGM.PERCCSL,0) ELSE 0 END) ELSE (CASE WHEN NVL(CGM.PERCCSL, 0) = 0 THEN 0 WHEN TGFTOP.TEMCSL = 'S'
                                                                                                                                                                                                       AND NOT EXISTS
(SELECT(1)
 FROM TGFDIN DIN
 WHERE DIN.CODIMP = 9
   AND DIN.NUNOTA = ITE.NUNOTA
   AND DIN.SEQUENCIA = ITE.SEQUENCIA) THEN NVL(CGM.PERCCSL, 0) ELSE 0 END) END) + (CASE WHEN CGM.TEMPERCPARTSIMP = 'S' THEN (CASE WHEN TGFTOP.TEMCOFINS = 'S' THEN NVL(CGM.PERCCOFINS,0) ELSE 0 END) ELSE (CASE WHEN NVL(CGM.PERCCOFINS, 0) = 0 THEN 0 WHEN TGFTOP.TEMCOFINS = 'S'
AND NOT EXISTS
  (SELECT(1)
   FROM TGFDIN DIN
   WHERE DIN.CODIMP = 7
     AND DIN.NUNOTA = ITE.NUNOTA
     AND DIN.SEQUENCIA = ITE.SEQUENCIA) THEN NVL(CGM.PERCCOFINS, 0) ELSE 0 END) END) + (CASE WHEN CGM.TEMPERCPARTSIMP = 'S' THEN (CASE WHEN TGFTOP.TEMPIS = 'S' THEN NVL(CGM.PERCIRPJ,0) ELSE 0 END) ELSE (CASE WHEN NVL(CGM.PERCIRPJ, 0) = 0 THEN 0 WHEN TGFTOP.TEMPIS = 'S'
AND NOT EXISTS
  (SELECT(1)
   FROM TGFDIN DIN
   WHERE DIN.CODIMP = 10
     AND DIN.NUNOTA = ITE.NUNOTA
     AND DIN.SEQUENCIA = ITE.SEQUENCIA) THEN NVL(CGM.PERCIRPJ, 0) ELSE 0 END) END) + (CASE WHEN CGM.TEMPERCPARTSIMP = 'S' THEN (CASE WHEN TGFTOP.TEMPIS = 'S' THEN NVL(CGM.PERCCPP,0) ELSE 0 END) ELSE (CASE WHEN NVL(CGM.PERCCPP, 0) = 0 THEN 0 WHEN TGFTOP.TEMPIS = 'S'
                                                                                                                                                                                                        AND NOT EXISTS
(SELECT(1)
 FROM TGFDIN DIN
 WHERE DIN.CODIMP = 11
   AND DIN.NUNOTA = ITE.NUNOTA
   AND DIN.SEQUENCIA = ITE.SEQUENCIA) THEN NVL(CGM.PERCCPP, 0) ELSE 0 END) END) + CASE WHEN CGM.TEMPERCPARTSIMP = 'S' THEN NVL(SNK_GetSomaPartilha(ITE.NUNOTA, ITE.SEQUENCIA), 0) ELSE 0 END)) + ((ITE.VLRTOT - ITE.VLRDESC - NVL(ITE.VLRREPRED,0) + ITE.VLRSUBST + ITE.VLRIPI) * VCA.INDITENS * (NVL(CGM.PERCCUSVAR,0) + NVL(CGM.PERCMARGEM,0) + NVL(TGFVEN.PERCCUSVAR,0) + NVL(0,0) + NVL(0,0) + NVL(0,0))) + ((ITE.VLRTOT - ITE.VLRDESC - NVL(ITE.VLRREPRED,0) + ITE.VLRIPI) * VCA.INDITENS * NVL(CGM.PERCCVARSEMST,0))) / 100.0000) + ITE.VLRSUBST + ITE.VLRIPI + (CASE WHEN CGM.TEMPERCPARTSIMP = 'S' THEN (0) ELSE ((NVL(
(SELECT SUM(CASE WHEN DIN.CODIMP = 1 THEN NVL(DIN.VLRDIFALDEST,0) + NVL(DIN.VLRDIFALREM,0) + NVL(DIN.VLRFCP,0) + NVL(DIN.VLRFCPINT,0) ELSE NVL(DIN.VALOR,0) END)
 FROM TGFDIN DIN
 WHERE DIN.NUNOTA = ITE.NUNOTA
   AND DIN.SEQUENCIA = ITE.SEQUENCIA
   AND DIN.CODIMP IN (1, 4, 5, 6, 7, 8, 9, 10, 11)), 0))) END)) + (CASE WHEN EMP.ICMSGERENCIA = 'N'
                                                                 OR (EMP.ICMSGERENCIA = 'P'
                                                                   AND TGFPRO.ICMSGERENCIA = 'N') THEN 0 WHEN 0 > 0 THEN 0 WHEN TGFCAB.VLRICMS = 0 THEN 0 ELSE ((ITE.VLRICMS - NVL(ITE.VLRREPRED,0)) * TGFCAB.VLRICMS / NVL(
(SELECT CASE WHEN SUM(ITE.VLRICMS - NVL(ITE.VLRREPRED,0)) = 0 THEN TGFCAB.VLRICMS ELSE SUM(ITE.VLRICMS - NVL(ITE.VLRREPRED,0)) END
 FROM TGFITE ITE
 WHERE ITE.NUNOTA = TGFCAB.NUNOTA
   AND ITE.SEQUENCIA > 0), TGFCAB.VLRICMS)) END) - 0 + (((ITE.VLRTOT - ITE.VLRDESC - NVL(ITE.VLRREPRED,0) + ITE.VLRSUBST + ITE.VLRIPI) * (CASE WHEN TIPIPIEMB = 'I' THEN VLREMB + IPIEMB + TGFCAB.VLRICMSEMB ELSE 0 END + VLRDESTAQUE + CASE WHEN TIPFRETE = 'S'
                                                                                                                                        OR CIF_FOB IN ('C', 'R') THEN VLRFRETE ELSE 0 END)/ CASE WHEN VCA.VLRITENS = 0 THEN 1 ELSE VCA.VLRITENS END) + ((ITE.VLRTOT - ITE.VLRDESC - NVL(ITE.VLRREPRED,0) + ITE.VLRSUBST + ITE.VLRIPI) * (CASE WHEN VCA.VLRITENS <> 0
AND TIPFRETE = 'N'
AND CIF_FOB IN ('C', 'R') THEN ICMSFRETE * -1 ELSE 0 END) / CASE WHEN VCA.VLRITENS = 0 THEN 1 ELSE VCA.VLRITENS END * CASE WHEN (VLRNOTA - VLRJURO + VLRDESCTOT - VLRDESTAQUE) = 0 THEN 1 ELSE (VLRNOTA / (VLRNOTA - VLRJURO + VLRDESCTOT - VLRDESTAQUE)) END)) + ((((ITE.VLRTOT - ITE.VLRDESC - CASE WHEN ITE.VLRREPRED > 0 THEN SNK_GET_ICMS_ESPECIAL_ITE(ITE.NUNOTA, ITE.SEQUENCIA, ITE.VLRREPRED, 'VLRREPRED') ELSE 0 END + ITE.VLRSUBST + ITE.VLRIPI) * VCA.INDITENS) * (NVL(TGFVEN.COMVENDA,0))) / 100)) - NVL((
(SELECT MAX(CUS.ENTRADASEMICMS)
 FROM TGFCUS CUS
 WHERE CUS.CODPROD = ITE.CODPROD
   AND ITE.CODEMP = CUS.CODEMP
   AND CUS.DTATUAL =
     (SELECT MAX (CN.DTATUAL)
      FROM TGFCUS CN
      WHERE CN.CODPROD = CUS.CODPROD
        AND CN.DTATUAL <= TGFCAB.DTNEG
        AND CN.CODLOCAl = CUS.CODLOCAL
        AND CN.CODEMP = CUS.CODEMP))), (ITE.VLRTOT - ITE.VLRDESC + ITE.VLRSUBST + ITE.VLRIPI) * VCA.INDITENS / (CASE WHEN ITE.QTDNEG=0 THEN 1 ELSE ITE.QTDNEG END)) * ITE.QTDNEG) * TGFTOP.GOLDEV AS "Margem de Contribuição",
        ((((((ITE.VLRTOT - ITE.VLRDESC - NVL(ITE.VLRREPRED,0)) * VCA.INDITENS * ((CASE WHEN CGM.TEMPERCPARTSIMP = 'S' THEN (CASE WHEN TGFTOP.TEMPIS = 'S' THEN NVL(CGM.PERCPIS,0) ELSE 0 END) ELSE (CASE WHEN NVL(CGM.PERCPIS, 0) = 0 THEN 0 WHEN TGFTOP.TEMPIS = 'S'
                                                                                                                                                                                                       AND NOT EXISTS
(SELECT(1)
 FROM TGFDIN DIN
 WHERE DIN.CODIMP = 6
   AND DIN.NUNOTA = ITE.NUNOTA
   AND DIN.SEQUENCIA = ITE.SEQUENCIA) THEN NVL(CGM.PERCPIS, 0) ELSE 0 END) END) + (CASE WHEN CGM.TEMPERCPARTSIMP = 'S' THEN (CASE WHEN TGFTOP.TEMCSL = 'S' THEN NVL(CGM.PERCCSL,0) ELSE 0 END) ELSE (CASE WHEN NVL(CGM.PERCCSL, 0) = 0 THEN 0 WHEN TGFTOP.TEMCSL = 'S'
                                                                                                                                                                                                   AND NOT EXISTS
                                                                                                                                                                                                     (SELECT(1)
                                                                                                                                                                                                      FROM TGFDIN DIN
                                                                                                                                                                                                      WHERE DIN.CODIMP = 9
                                                                                                                                                                                                        AND DIN.NUNOTA = ITE.NUNOTA
                                                                                                                                                                                                        AND DIN.SEQUENCIA = ITE.SEQUENCIA) THEN NVL(CGM.PERCCSL, 0) ELSE 0 END) END) + (CASE WHEN CGM.TEMPERCPARTSIMP = 'S' THEN (CASE WHEN TGFTOP.TEMCOFINS = 'S' THEN NVL(CGM.PERCCOFINS,0) ELSE 0 END) ELSE (CASE WHEN NVL(CGM.PERCCOFINS, 0) = 0 THEN 0 WHEN TGFTOP.TEMCOFINS = 'S'
AND NOT EXISTS
  (SELECT(1)
   FROM TGFDIN DIN
   WHERE DIN.CODIMP = 7
     AND DIN.NUNOTA = ITE.NUNOTA
     AND DIN.SEQUENCIA = ITE.SEQUENCIA) THEN NVL(CGM.PERCCOFINS, 0) ELSE 0 END) END) + (CASE WHEN CGM.TEMPERCPARTSIMP = 'S' THEN (CASE WHEN TGFTOP.TEMPIS = 'S' THEN NVL(CGM.PERCIRPJ,0) ELSE 0 END) ELSE (CASE WHEN NVL(CGM.PERCIRPJ, 0) = 0 THEN 0 WHEN TGFTOP.TEMPIS = 'S'
AND NOT EXISTS
  (SELECT(1)
   FROM TGFDIN DIN
   WHERE DIN.CODIMP = 10
     AND DIN.NUNOTA = ITE.NUNOTA
     AND DIN.SEQUENCIA = ITE.SEQUENCIA) THEN NVL(CGM.PERCIRPJ, 0) ELSE 0 END) END) + (CASE WHEN CGM.TEMPERCPARTSIMP = 'S' THEN (CASE WHEN TGFTOP.TEMPIS = 'S' THEN NVL(CGM.PERCCPP,0) ELSE 0 END) ELSE (CASE WHEN NVL(CGM.PERCCPP, 0) = 0 THEN 0 WHEN TGFTOP.TEMPIS = 'S'
                                                                                                                                                                                                        AND NOT EXISTS
(SELECT(1)
 FROM TGFDIN DIN
 WHERE DIN.CODIMP = 11
   AND DIN.NUNOTA = ITE.NUNOTA
   AND DIN.SEQUENCIA = ITE.SEQUENCIA) THEN NVL(CGM.PERCCPP, 0) ELSE 0 END) END) + CASE WHEN CGM.TEMPERCPARTSIMP = 'S' THEN NVL(SNK_GetSomaPartilha(ITE.NUNOTA, ITE.SEQUENCIA), 0) ELSE 0 END)) + ((ITE.VLRTOT - ITE.VLRDESC - NVL(ITE.VLRREPRED,0) + ITE.VLRSUBST + ITE.VLRIPI) * VCA.INDITENS * (NVL(CGM.PERCCUSVAR,0) + NVL(CGM.PERCMARGEM,0) + NVL(TGFVEN.PERCCUSVAR,0) + NVL(0,0) + NVL(0,0) + NVL(0,0))) + ((ITE.VLRTOT - ITE.VLRDESC - NVL(ITE.VLRREPRED,0) + ITE.VLRIPI) * VCA.INDITENS * NVL(CGM.PERCCVARSEMST,0))) / 100.0000) + ITE.VLRSUBST + ITE.VLRIPI + (CASE WHEN CGM.TEMPERCPARTSIMP = 'S' THEN (0) ELSE ((NVL(
(SELECT SUM(CASE WHEN DIN.CODIMP = 1 THEN NVL(DIN.VLRDIFALDEST,0) + NVL(DIN.VLRDIFALREM,0) + NVL(DIN.VLRFCP,0) + NVL(DIN.VLRFCPINT,0) ELSE NVL(DIN.VALOR,0) END)
 FROM TGFDIN DIN
 WHERE DIN.NUNOTA = ITE.NUNOTA
   AND DIN.SEQUENCIA = ITE.SEQUENCIA
   AND DIN.CODIMP IN (1, 4, 5, 6, 7, 8, 9, 10, 11)), 0))) END)) + (CASE WHEN EMP.ICMSGERENCIA = 'N'
                                                                 OR (EMP.ICMSGERENCIA = 'P'
                                                                   AND TGFPRO.ICMSGERENCIA = 'N') THEN 0 WHEN 0 > 0 THEN 0 WHEN TGFCAB.VLRICMS = 0 THEN 0 ELSE ((ITE.VLRICMS - NVL(ITE.VLRREPRED,0)) * TGFCAB.VLRICMS / NVL(
(SELECT CASE WHEN SUM(ITE.VLRICMS - NVL(ITE.VLRREPRED,0)) = 0 THEN TGFCAB.VLRICMS ELSE SUM(ITE.VLRICMS - NVL(ITE.VLRREPRED,0)) END
 FROM TGFITE ITE
 WHERE ITE.NUNOTA = TGFCAB.NUNOTA
   AND ITE.SEQUENCIA > 0), TGFCAB.VLRICMS)) END) - 0 + (((ITE.VLRTOT - ITE.VLRDESC - NVL(ITE.VLRREPRED,0) + ITE.VLRSUBST + ITE.VLRIPI) * (CASE WHEN TIPIPIEMB = 'I' THEN VLREMB + IPIEMB + TGFCAB.VLRICMSEMB ELSE 0 END + VLRDESTAQUE + CASE WHEN TIPFRETE = 'S'
                                                                                                                                        OR CIF_FOB IN ('C', 'R') THEN VLRFRETE ELSE 0 END)/ CASE WHEN VCA.VLRITENS = 0 THEN 1 ELSE VCA.VLRITENS END) + ((ITE.VLRTOT - ITE.VLRDESC - NVL(ITE.VLRREPRED,0) + ITE.VLRSUBST + ITE.VLRIPI) * (CASE WHEN VCA.VLRITENS <> 0
AND TIPFRETE = 'N'
AND CIF_FOB IN ('C', 'R') THEN ICMSFRETE * -1 ELSE 0 END) / CASE WHEN VCA.VLRITENS = 0 THEN 1 ELSE VCA.VLRITENS END * CASE WHEN (VLRNOTA - VLRJURO + VLRDESCTOT - VLRDESTAQUE) = 0 THEN 1 ELSE (VLRNOTA / (VLRNOTA - VLRJURO + VLRDESCTOT - VLRDESTAQUE)) END)) + ((((ITE.VLRTOT - ITE.VLRDESC - CASE WHEN ITE.VLRREPRED > 0 THEN SNK_GET_ICMS_ESPECIAL_ITE(ITE.NUNOTA, ITE.SEQUENCIA, ITE.VLRREPRED, 'VLRREPRED') ELSE 0 END + ITE.VLRSUBST + ITE.VLRIPI) * VCA.INDITENS) * (NVL(TGFVEN.COMVENDA,0))) / 100)) * TGFTOP.GOLDEV AS "Gasto Variável",
        ITE.QTDNEG AS "Volume de Vendas"

FROM TGFCAB ,
   TGFITE ITE ,
   TGFTOP ,
   VGFCAB VCA ,
   TGFEMP EMP ,
   TGFCGM CGM ,
   TGFVEN ,
   TGFPRO,
   TSIEMP EMPE
WHERE TGFCAB.STATUSNOTA = 'L'
AND TGFCAB.NUNOTA = ITE.NUNOTA
AND TGFCAB.NUNOTA = VCA.NUNOTA
AND TGFCAB.CODEMP = EMP.CODEMP
AND ITE.SEQUENCIA > 0
AND TGFCAB.CODTIPOPER = TGFTOP.CODTIPOPER
AND TGFCAB.DHTIPOPER = TGFTOP.DHALTER
AND TGFTOP.GOLSINAL = -1
AND TGFCAB.CODVEND = TGFVEN.CODVEND
AND EMPE.CODEMP = TGFCAB.CODEMP
AND (NOT EXISTS
       (SELECT 1
        FROM TGFVAR VAR
        WHERE VAR.NUNOTA = ITE.NUNOTA
          AND VAR.NUNOTAORIG = VAR.NUNOTA
          AND VAR.SEQUENCIAORIG = ITE.SEQUENCIA))
AND ITE.CODPROD = TGFPRO.CODPROD
AND CGM.CODEMP = EMP.CODEMP
AND CGM.DTREF =
(SELECT MAX(C.DTREF)
 FROM TGFCGM C
 WHERE C.CODEMP = EMP.CODEMP
   AND C.DTREF <= TGFCAB.DTNEG)
AND EXISTS
(SELECT 1
 FROM TGFCUS CUS
 WHERE CUS.CODPROD = ITE.CODPROD
   AND CUS.DTATUAL <= TGFCAB.DTENTSAI)
AND (TGFCAB.CODTIPOPER IN (1000))
AND ((TGFTOP.GOLSINAL = -1
      AND TGFTOP.GOLDEV = 1
       )
     OR (TGFTOP.GOLSINAL = -1
         AND TGFTOP.GOLDEV = -1
         ))
